### ISSUE TITLE
No sound after connecting, not sure what the issue is

### ISSUE THREAD

**Issue by Savasdotexe** [mkckr0/audio-share#25] opened 2024-01-01 11:21 UTC
**Describe the bug** / **To Reproduce**
I run the program AudioShareServer.exe as instructed, I make sure the host/IP & port is the same as the PC it's running on. I select the audio endpoint as my speaker and press start. It changes to "Stop Server".

On Android I started the app and made sure the Host & Port matches with the host/IP & port above. I press the play button which changes to a pause icon.

I then start some kind of sound on the PC.

**Expected behavior**
I should expect it to play on the android app? No sound from the android device. Everything seems to be running, no errors..

**Server (please complete the following information):**
 - OS: Windows 11 Home 22H2
 - CPU: AMD Ryzen 5 5600H with Radeon Graphics            3.30 GHz
 - GUI or CMD: GUI
 - Version 0.0.14.0

**Android (please complete the following information):**
 - Device: Samsung Galaxy A52S 5G / SM-A528B/DS
 - OS: Android 14
 - Version 0.0.14.0

**log**
```
[2024-01-01 11:12:00.985] [server] [info] tcp listen success on 192.168.1.5:65530
[2024-01-01 11:12:00.985] [server] [info] endpoint_id: {0.0.0.00000000}.{########-####-####-####-#######}
[2024-01-01 11:12:00.986] [server] [info] udp listen success on 192.168.1.5:65530
[2024-01-01 11:12:00.986] [server] [info] server started
[2024-01-01 11:12:00.986] [server] [info] select audio endpoint: Panasonic-TV (NVIDIA High Definition Audio)
[2024-01-01 11:12:00.989] [server] [info] WAVEFORMATEX: wFormatTag: 65534, nBlockAlign: 8
[2024-01-01 11:12:00.990] [server] [info] AudioFormat:
format_tag: 3
channels: 2
sample_rate: 48000
bits_per_sample: 32

[2024-01-01 11:12:00.999] [server] [info] buffer size: 480000
[2024-01-01 11:12:01.000] [server] [info] deivce period: 3ms
[2024-01-01 11:12:13.982] [server] [info] accept 192.168.1.6:58206
[2024-01-01 11:12:28.924] [server] [info] server stopped
```

**Comment by mkckr0** [comment] 2024-01-01 12:13
The app and server started normally. Does your volume of PC or phone tune to max?

**Comment by Savasdotexe** [comment] 2024-01-01 12:47
> Does your volume of PC or phone tune to max?
Not sure what you mean. When I press volume up, both PC and phone volumes do adjust and I am able to bring it to maximum, yes. For example when I play something on mpv player on the PC I hear the sound on the PC, but not the phone. I tried putting the phone to full volume while the app is open, nothing happens.

> Does the speaker of phone work normally?
As in using say YouTube and testing it? Yes, I can hear it.

**Comment by mkckr0** [comment] 2024-01-01 13:49
Open the task manager when AudioShareServer.exe is running to see whether have network traffic.
![capture](https://github.com/mkckr0/audio-share/assets/26296627/c5926c06-2c5c-4fae-8889-9a39d54ed154)

**Comment by mkckr0** [comment] 2024-01-01 14:14
When checking the task manager, you need start the app and play some sound. The traffic monitor of phone may disturb the app, don't use it.

After all things have been done, check the task manager again.

**Comment by Savasdotexe** [comment] 2024-01-01 14:30
Yup, that's what I did. Played a full track for about 1 minute.

**Comment by mkckr0** [comment] 2024-01-01 14:35
The AudioShareServer.exe can't capture any sound. Check whether the default audio endpoint is "Panasonic-TV (NVIDIA High Definition Audio)", which should be the same you selected in AudioShareServer.exe

![1](https://github.com/mkckr0/audio-share/assets/26296627/d1ca8c36-a556-4830-8c86-253215c303d7)

**Comment by Savasdotexe** [comment] 2024-01-01 14:41
Just double checked, yes it is.

![screenshot-2024-01-01_143943](https://github.com/mkckr0/audio-share/assets/4998569/b52895f4-6fc5-430f-a50c-c0bcac73a8c6)

**Comment by mkckr0** [comment] 2024-01-01 14:57
I see the second line of log is
```
[2024-01-01 11:12:00.985] [server] [info] endpoint_id: {0.0.0.00000000}.{########-####-####-####-#######}
```
The second part shouldn't been all "#". Do you modify it or it's that originally.

**Comment by mkckr0** [comment] 2024-01-02 12:34
I guess it may be caused by the firewall. Please delete these entries in wf.msc and restart the AudioShareServer.exe
![image](https://github.com/mkckr0/audio-share/assets/26296627/f9cfa01e-2a8e-4d72-b289-a520e0709d13)

**Comment by Savasdotexe** [comment] 2024-01-02 16:06
> The second part shouldn't been all "#". Do you modify it or it's that originally?

Yes, that's right. Wasn't sure if it was personal information.

**Comment by mkckr0** [comment] 2024-01-03 01:48
The rule name may be "Audio Share Server" or "audioshareserver.exe" in "Inbound Rules", delete them all and restart the "AudioShareServer.exe".

Don't create the rule manually. There is a firewall alert dialog when click "Start Server". Remain the default options and click "Allow access".
![image](https://github.com/mkckr0/audio-share/assets/26296627/563d8e5e-8d0e-429b-b026-72ebc865118d)

**Comment by mkckr0** [comment] 2024-01-03 15:19
Disbling uPnP may increase dropping UDP frame, but it's not the reason.

The rules can be sorted by "Program" and it's easy to find rules which is same as the location of "AudioShareServer.exe".
After delete the rules, you must really exit the "AudioShareServer.exe" and restart it. Then the dialog will show up.

**Comment by Savasdotexe** [comment] 2024-01-05 18:22
> The rules can be sorted by "Program" and it's easy to find rules which "Program" is same as the location of "AudioShareServer.exe".

I even exported the full list inbound and outbound firewall rules and made sure it's not added, searched "audio" and nothing. Can confirm, after triple checking.

**Comment by mkckr0** [comment] 2024-01-06 03:12
At past time, did you see the dialog when your first time clicked the "Start Server"?
If no, I also don't have any better measure to take.

You can close the firewall temporarily and restart the "AudioShareServer.exe" to ensure the firewall is the main reason.

**Comment by mkckr0** [comment] 2024-01-15 02:25
I'll close this issue. If you still have problem, you can reopen it.

**Closed by mkckr0** 2024-01-15 02:25 UTC
Labels: bug
